# 连接数据库的配置信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.220.169.221:3306/mall_ams?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# 日志的显示级别
logging:
  level:
    cn:
      org:
        sqx:
          mall: trace

# JWT密钥，注意：最短需要4个字符，推荐使用20字符以上，且应该由大写字母、小写字母、数字、标点符号组成
mall:
   jwt:
     secret-key: mjqhrgx
